services:
  review-service:
    #    build: ./review-service
    #    image: review-service:v1.0.0
    image: ecom-review-service:latest
    container_name: review-service
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - ecom-network

networks:
  ecom-network:
    external: true
