services:
  product-service:
    #    build: ./product-service
    #    image: product-service:v1.0.0
    image: ecom-product-service:latest
    container_name: product-service
    ports:
      - "8086:8086"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - ecom-network

networks:
  ecom-network:
    external: true
