services:
  coupon-service:
    #    build: ./coupon-service
    #    image: coupon-service:v1.0.0
    image: ecom-coupon-service:latest
    container_name: coupon-service
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - ecom-network


networks:
  ecom-network:
    external: true
